### ISSUE TITLE
Jellyfin not starting with windows startup with error Could not find file 'D:\Program\Jellyfin\Server\jellyfin.deps.json'.

### ISSUE THREAD

**Issue by lihuiby** [jellyfin/jellyfin-server-windows#112]
when the first install Jellyfin start success . but when restart . 
the log print System.IO.FileNotFoundException: Could not find file 'D:\Program\Jellyfin\Server\jellyfin.deps.json'.

**Comment by anthonylavado** [comment]
Has this occurred again with any of the 10.9 versions?
