### ISSUE TITLE
Jellyfin Service missing on Windows

### ISSUE THREAD

**Issue by BB-Forrest** [jellyfin/jellyfin-server-windows#118]
### Please describe your bug

I've just upgraded from 10.8.13 to 10.9.1

My Jellyfin service in Windows has disapeared and the tray app will not open as it says the service is not running.

### Reproduction Steps

Downloaded new release from jellyfin.org - AMD64 version, upgraded jellyfin, it uninstalled the service and didn't create a new one.

### Jellyfin Version

10.9.0

### if other:

10.9.1

### Environment

```markdown
- OS: Windows 11 (latest)
- Virtualization: None
```

### Jellyfin logs

```shell
Not able to get as not running
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anthonylavado** [comment]
Are you able to try running the installer again in place? It should try to recreate any missing pieces.

**Comment by anthonylavado** [comment]
Should mention - download the installer again, don't just use the one already downloaded. A "good" copy is 133,716 KB.

**Comment by BB-Forrest** [comment]
Tried that originally, did nothing.

So, I downloaded 10.9, installed that and it installs the service.

Downloaded the portable version of 10.9.1, stopped the service, copied the extracted files over the install of 10.9 and started the service again, it's now working.

Not certain that it's a valid workaround for some people but it is the only way that I could get it to work.

**Comment by anthonylavado** [comment]
That's really strange, as there's nothing different in the installer code from one version to the next...

I'll have to investigate further and try an in place upgrade from 10.8.13 to 10.9.1 on a test system.

In the service mode, were you using Local System or Network Service as the account?

**Comment by BB-Forrest** [comment]
You can use either (I'm an ex MCSE dealing with SQL Server these days but
can still talk O/S's with server people.

When I tried the upgrade it never gave the option, just removed the service
(could see the command) but didn't then create it at the end of the
install.
