### ISSUE TITLE
Windows installer failure in case of upgrade

### ISSUE THREAD

**Issue by crankdoofus** [jellyfin/jellyfin-server-windows#123]
Seen while upgrading windows install from 10.8.x tp 10.9.0, then again from 10.9.0 -> 10.9.1 and now from 10.9.1 -> 10.9.2
1. Jellyfin is running as service
2. Running installer displays an error - Jellyfin is running, it needs to be closed.
3. The service is stopped manually
4. Installer is run again
5. It detects existing installation
6. Choose to retain data at the option
7. Installer invokes silent uninstall as intended
But now since the service was stopped prior to installation, the uninstaller fails. The handling isn't correct to recover from this error and installer just freezes doing nothing.

The only way to recover is to quit the installer and restart it. 
But now it has lost all the prior settings because the earlier silent uninstall cleaned up the registry before failing.

Let me know if you need more details.
Clean installing 10.9.0 as a service and then trying to install 10.9.1 (or 10.9.2) should be able to repro the issue easily.

**Comment by crankdoofus** [comment]
same as https://github.com/jellyfin/jellyfin/issues/11726. 
Please determine the appropriate repo and close the other.

Repeating my comment here : 
this has been introduced from this commit - 6efa17b : https://github.com/jellyfin/jellyfin-server-windows/commit/6efa17bc3a5ec1c036c3d1dbee8fa8e7966f8e0c

@anthonylavado - this might have been introduced to close tray app before proceeding, it need a check for EXISTINGSERVICE

**Comment by anthonylavado** [comment]
Thanks for this. It wasn't to close the tray app, but to make sure Jellyfin is closed because people often don't do so before running the setup.

The installer is really a house of cards that I've tried to improve a little bit after so many years.

I'll group a fix to the logic for this along with the fix for an older .NET framework.

**Comment by strigona** [comment]
Hey, not sure if I'm missing something, but the issue is persisting with 10.9.4.

I tried both not stopping the server before running the installer (got the error), then shutdown the server and re-ran the installer and got the following error.

![image](https://github.com/jellyfin/jellyfin-server-windows/assets/246258/2ea2b818-7344-4cfd-ae92-4f06a6407a04)

**Comment by mattish91** [comment]
> Hey, not sure if I'm missing something, but the issue is persisting with 10.9.4.
> 
> I tried both not stopping the server before running the installer (got the error), then shutdown the server and re-ran the installer and got the following error.
> 
> ![image](https://private-user-images.githubusercontent.com/246258/335938847-2ea2b818-7344-4cfd-ae92-4f06a6407a04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0NTI5ODcsIm5iZiI6MTcxNzQ1MjY4NywicGF0aCI6Ii8yNDYyNTgvMzM1OTM4ODQ3LTJlYTJiODE4LTczNDQtNGNmZC1hZTkyLTRmMDZhNjQwN2EwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwM1QyMjExMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZjAzZmUzYTc3NjQ2ZWJlZDcyN2U3MjJmZGE1MTAwMjBiMjJjZDNiMjA1ZTc5NzM2NzZmNGIyZGI2ZTZiODA2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-jqBOgS2dznCcA-H1rAZIS3tSWsbVWJv_b0JzQrnksI)

Gonna test this right now just to confirm this is still the case. Mainly since i wan't to be on the latest version as i have a script that i run to update everything automatically.
