### ISSUE TITLE
Tray app does not read in non-standard server port for "Open Jellyfin"

### ISSUE THREAD

**Issue by solidsnake1298** [jellyfin/jellyfin-server-windows#126]
The Windows tray app does not read in the http port number.  It will always fail to default 8096.

https://github.com/jellyfin/jellyfin-server-windows/blob/master/Jellyfin.Windows.Tray/TrayApplicationContext.cs

The tray app attempts to read in ```HttpServerPortNumber``` but the variable is now called ```InternalHttpPort``` in network.xml for server version 10.9+.

Clicking "open jellyfin" will always open on port 8096.  Even if a custom port is set.

**Comment by shaneo88** [comment]
I am also having this issue.

I have 8097 set for my pain pc and 8096 set for my laptop, because I'd like to access them both from outside of my local network

**Comment by anthonylavado** [comment]
I'll be fixing this for the next release, due very soon.
