### ISSUE TITLE
[issue]: 10.9.4 Windows tray app still opening on port 8096

### ISSUE THREAD

**Issue by shaneo88** [jellyfin/jellyfin-server-windows#131]
I have updated to Jellyfin Server 10.9.4 and after doing a computer restart, manually stopping, closing and restarting Jellyfin and also clearing browser cookies, Jellyfin is 100% still opening port 8096 when right clicking the tray app and selecting Open Jellyfin. 

I have checked the network.xml file and also the networking tab in Jellyfin settings and they both say port 8097 is set. 

I cleared my logs while doing the computer/Jellyfin restart and there is nothing about ports in the logs after trying to open from the tray app. 

I have added a log and all the screenshots I can think of.

![IMG_6458](https://github.com/jellyfin/jellyfin-server-windows/assets/5802211/dfcd741e-41a6-428c-99c1-2dc5414c73ba)
![IMG_6459](https://github.com/jellyfin/jellyfin-server-windows/assets/5802211/4c2902c5-93a9-4659-ab19-2a910f644743)
![IMG_6460](https://github.com/jellyfin/jellyfin-server-windows/assets/5802211/69298fe0-5fc5-4df3-a1af-24515d919d95)
![open jellyfin](https://github.com/jellyfin/jellyfin-server-windows/assets/5802211/80ab7de4-f431-40e5-9d7b-db8deff9bec4)
![Uploading open jellyfin2.png…]()

[log_20240603.log](https://github.com/user-attachments/files/15529606/log_20240603.log)

**Comment by anthonylavado** [comment]
Yes, I think I got the XML field incorrect in the last fix. I'm tracking down the service logic error and then fixing this.

**Comment by shaneo88** [comment]
Awesome. Thanks
