### ISSUE TITLE
jellyfin.exe missing after Windows update

### ISSUE THREAD

**Issue by Lillebo** [jellyfin/jellyfin-server-windows#24]
Just updated my Windows 10 and suddenly the `jellyfin.exe` file is missing from the `server` directory.

The update in question is:
>Security Intelligence Update for Windows Defender Antivirus - KB2267602 (Version 1.313.1802.0)

**Comment by Hoshigamifd** [comment]
ME TOO !! Only I open jellyfin with view console mode.

**Comment by anthonylavado** [comment]
Hrm. Haven't had this come up before. Is it the tray app that's missing, or is Jellyfin.exe actually gone?

**Comment by Lillebo** [comment]
Jellyfin.exe is actually gone 😕 Could you provide a download link for a replacement file so I don't have to reinstall everything and risk losing my meta stuff? I'm on Windows 10 Pro, 64bit.

![explorer_JPJYp2bnvf](https://user-images.githubusercontent.com/74510/80245058-4e81b480-866a-11ea-919a-df8bb27f40a5.png)

**Comment by anthonylavado** [comment]
You can download the ZIP (not the install EXE) and it'll be inside there. Again, I don't think this has happened before. If you suspect a Windows Defender update has removed it, check the Defender logs to see why it was detected/deleted.

**Comment by Lillebo** [comment]
I tried downloading the zip and extracting jellyfin.exe into my server directory. But absolutely nothing happens when I try to run the file. No errors, nothing. Running as administrator has no effect either.

**Comment by anthonylavado** [comment]
We have a new version available now, so if you download it, it will act as an upgrade for you. The upgrade would put a new Jellyfin.exe and other files too.

**Comment by Lillebo** [comment]
Upgrading to the latest version fixed it, thanks 🙂

**Comment by Hoshigamifd** [comment]
@Lillebo  thanks .
when I click actor picture with upgrading to  the new version , loading so slow(about 20s).
I restore the old version, becomes smoothly. And some movies UI become very large ,
can't dis[lay "play, delete, watched" icons  :(

**Comment by Hoshigamifd** [comment]
@anthonylavado thanks .
when I click actor picture with upgrading to  the new version , loading so slow(about 20s).
I have to restore the old version, makes very smoothly. And some movies UI become very large ,
can't dis[lay "play, delete, watched" icons.  :(

**Comment by anthonylavado** [comment]
> when I click actor picture with upgrading to the new version , loading so slow(about 20s).
> I have to restore the old version, makes very smoothly. And some movies with long name UI become very large ,
> can't dis[lay "play, delete, watched" icons. :(

@hoshigamifd I think these issues are listed on the jellyfin/jellyfin-web repository. If you haven't yet, I would check there and vote for them :)

**Comment by seguri** [comment]
I've just downloaded all archives from https://repo.jellyfin.org/?path=/server/portable/latest-stable/any and `jellyfin.exe` is missing from all archives...

**Comment by nielsvanvelzen** [comment]
The portable windows builds can be found in https://repo.jellyfin.org/?path=/server/windows/latest-stable/amd64

**Comment by seguri** [comment]
Thanks. If the portable version is also under `/server/windows`, the docs at https://jellyfin.org/downloads/windows/ might need to get fixed.

**Comment by nielsvanvelzen** [comment]
Those docs are correct although not very clear. The "dotnet portable" version requires a dotnet runtime and you'll need to run it from the commandline like so `dotnet jellyfin.dll`. It's platform independent so that download works on any OS as long as you have a dotnet runtime installed.
