### ISSUE TITLE
Updating the Tray App

### ISSUE THREAD

**Issue by anthonylavado** [jellyfin/jellyfin-server-windows#28]
There are several steps involved in preparing the tray app for Jellyfin 10.6:

## Build/Infrastructure Work
- [x] Remove the single file and trimmed publish options (ref [.csproj](https://github.com/jellyfin/jellyfin-server-windows/blob/5878dc7e50dd389e96f41279ee9146b3e9441c0f/Jellyfin.Windows.Tray/Jellyfin.Windows.Tray.csproj#L9-L10))
- [x] Investigate what DLLs are used by the tray app, and if there are any unique ones not shared with a regular Jellyfin install for Windows
- [x] Set up a build that creates a [self-contained deployment](https://docs.microsoft.com/en-us/dotnet/core/deploying/#publish-self-contained), and removes DLLs that would be shared with Jellyfin server
- [x] Make this build happen in Azure Pipelines

## Tray App 

- [x] Update to latest stable .NET Core version that matches the server as well
- [x] Update to read more of the server's configuration from the on-disk system.xml as needed
- [x] Provide better error messages during any startup issues

---

This is part of a larger restructuring effort to improve the experience on Windows.

**Comment by sunnyd24** [comment]
Is there anyway to "Autostart" server console from Tray App by default, or alternatively allow the console to be by default through configuration settings when using the "basic install" method with windows installer?

I am not seeing any of these options available in the tray app or server configuration files in 10.7.7 x64, unless I am missing something......?

**Comment by sunnyd24** [comment]
@anthonylavado Yes, with console window running by default on boot/user log in.

Brill, adding that into the tray app would be really useful for the future, especially when debugging playback issues, etc.

Ok, that's what I have been using but manually, good suggestion to add into startup folder and I will also have to disable "Autostart" in tray app.
