### ISSUE TITLE
Jellyfin tray deletes itself after a system reset.

### ISSUE THREAD

**Issue by Darkwolf1515** [jellyfin/jellyfin-server-windows#35]
No idea why, I closed the app, restarted windows, went to boot the tray from the shortcut, but the exe was missing.

**Comment by anthonylavado** [comment]
If you downloaded the update before 3:10 AM EDT/7:10 AM UTC, then please redownload it and install over your existing version. It will add the better tray app that shouldn't have that problem.

**Comment by anthonylavado** [comment]
Is this still happening for you @Darkwolf1515 or is everything okay now? 🙂

**Comment by Darkwolf1515** [comment]
> 
> 
> Is this still happening for you @Darkwolf1515 or is everything okay now? 🙂

Ah yeah, sorry, it works just fine, thank you, Ill close it.
