### ISSUE TITLE
Missing dependencies for Windows Server Core

### ISSUE THREAD

**Issue by Bix-Nood-Networks** [jellyfin/jellyfin-server-windows#40]
Jellyfin, or perhaps more specifically ffmpeg doesnt work on Windows Server Core as it has dependencies on DLLs only present on a Desktop Experience edition of Windows. You might want to have the installer or HTTP service check and alert the user to this so they dont wonder why videos will play back. It needs the following DLLs from %WINDIR%\system32

AVICAP32.dll
MSVFW32.dll
MFPlat.dll
dxva32.dll

And possibly others

**Comment by Ediblewildfungi** [comment]
I downloaded those DLL files, but they didn't work. I tried the following methods to make it work successfully:

1. Open "control panel",
2. find "Microsoft.ProgramsAndFeatures" - > "turn windows features on or off"
3. “next“ “next” “next” “next”until the ”features“ option appears
4. add "Quality Windows Audio/Video Experience" （qwave）
5. Wait until the installation is complete, restart the system and jellyfin server

My Windows system language is Chinese, and some translation may be inaccurate 🤣
i hope that would be useful for you.

**Comment by besweeet** [comment]
> I downloaded those DLL files, but they didn't work. I tried the following methods to make it work successfully:
> 
> 1. Open "control panel",
> 2. find "Microsoft.ProgramsAndFeatures" - > "turn windows features on or off"
> 3. “next“ “next” “next” “next”until the ”features“ option appears
> 4. add "Quality Windows Audio/Video Experience" （qwave）
> 5. Wait until the installation is complete, restart the system and jellyfin server
> 
> My Windows system language is Chinese, and some translation may be inaccurate 🤣 i hope that would be useful for you.

Tried this on Windows Server 2012 R2. Installed qWAVE, restarted, and I still get the missing MFPlat.dll error.

**Comment by anthonylavado** [comment]
@besweeet I don't know if the other users were working with 2012R2 or not, so you might need a bit more.

A quick search shows that Roon had a similar issue, where they directed people to install this: https://www.microsoft.com/en-us/download/details.aspx?id=40837

**Comment by besweeet** [comment]
> @besweeet I don't know if the other users were working with 2012R2 or not, so you might need a bit more.
> 
> A quick search shows that Roon had a similar issue, where they directed people to install this: https://www.microsoft.com/en-us/download/details.aspx?id=40837
I failed to update my comment, but that did the trick.
