### ISSUE TITLE
x86 build would fail because Zeranoe builds don't exist anymore

### ISSUE THREAD

**Issue by HimbeersaftLP** [jellyfin/jellyfin-server-windows#41]
Context:
- https://twitter.com/Zeranoe/status/1300596971934224385
- https://github.com/jellyfin/jellyfin-server-windows/blob/0945956643a7d932b5f3d25a79dd9ceafeb5010c/build-jellyfin.ps1#L64

Possible solutions:
- Remove x86 building completely, as [the docs](https://jellyfin.org/docs/general/administration/installing.html) mention it's deprecated anyways
- Add x86 Windows builds to https://github.com/jellyfin/jellyfin-ffmpeg/releases

Note that I haven't tried if they would fail for another reason, too.

**Comment by anthonylavado** [comment]
Ah thank you for bringing this up - I believe we package our own at this moment (though of course we should document that better).
