### ISSUE TITLE
jellyfin tray - open jellyfin point s to local host

### ISSUE THREAD

**Issue by Cozy59** [jellyfin/jellyfin-server-windows#47]
Hi all i was looking around as a newbie because I stumbeled over an issue which I cant resolve. When Jellyfin Tray is started the menu gives you the option to open Jellyfin which will be started in a browser window. 
Now updated from 10.6.4 to 10.7.1 starts the browser to localhost. However I changed Jellyfin in networking to an other local ip-adress. What do I do wrong or is there a way to point this open Jellyfin to another changed IP address?  Thanks in advance for help or suggestions.

**Comment by anthonylavado** [comment]
You haven't done anything wrong. It's currently hard coded to localhost with no option to change it.

I already load the port from the config, so it should be an easy enough change to also load the listening interface/IP address.

**Comment by Cozy59** [comment]
Thanx for the quick reply. I will wait for the fix/update and till then work with a workaround.

**Comment by anthonylavado** [comment]
@Cozy59 - Hey there, just to follow up, did you set the "Bind to local network address" setting?

**Comment by Cozy59** [comment]
Hi Anthony Yes I did.  Grtz Cozy Verzonden vanuit Mail voor Windows 10 Van: Anthony LavadoVerzonden: zondag 25 april 2021 05:36Aan: jellyfin/jellyfin-server-windowsCC: Cozy59; MentionOnderwerp: Re: [jellyfin/jellyfin-server-windows] jellyfin tray - open jellyfin point s to local host (#47) @Cozy59 - Hey there, just to follow up, did you set the "Bind to local network address" setting?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by anthonylavado** [comment]
This should be fixed in the 10.7.5 release. I'll put up the matching PR soon.

**Comment by Cozy59** [comment]
Thanx Anthony  Looking forward to the new release RegardsCozy Verzonden vanuit Mail voor Windows 10 Van: Anthony LavadoVerzonden: vrijdag 7 mei 2021 17:27Aan: jellyfin/jellyfin-server-windowsCC: Cozy59; MentionOnderwerp: Re: [jellyfin/jellyfin-server-windows] jellyfin tray - open jellyfin point s to local host (#47) This should be fixed in the 10.7.5 release. I'll put up the matching PR soon.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
