### ISSUE TITLE
error message - "When running Jellyfin as a service, the tray application must be run as administrator"

### ISSUE THREAD

**Issue by happyguy1** [jellyfin/jellyfin-server-windows#56]
this is an error message i am getting after each time i reboot:

"When running Jellyfin as a service, the tray application must be run as administrator"

![sshot-1](https://user-images.githubusercontent.com/4994157/159593498-17adaef0-176c-4fd6-b490-b24e228e6e6b.jpg)

the only solution i found is to click ok, and then exit from the system tray, and then run a shortcut of the jellyfin tray executable that is set to run as administrator - and i have to do this after each reboot.

I really don't want to have to uninstall and reinstall, given all the hours i manually put into getting the metadata correct - is there another solution?

**Comment by happyguy1** [comment]
btw, i may be the first person to get this error as there is no mention of it on a google search:

https://www.google.com/search?client=firefox-b-1-d&q=%22When+running+Jellyfin+as+a+service%2C+the+tray+application+must+be+run+as+administrator%22

![jfin2](https://user-images.githubusercontent.com/4994157/159603800-79db0d55-235e-4b29-811d-ed9f359c5b37.jpg)

**Comment by happyguy1** [comment]
another temporary solution is to use autoruns and disable the autostart of the jellyfin tray - but once you run jellyfin, the software puts another tray entry into autostart run

if i uninstall jellyfin, can i somehow save the metadata and then re-install to not run as a service and connect the saved metadata?

or is there another solution?

thanks much - i love jellyfin!

**Comment by anthonylavado** [comment]
If it's running as a service, you don't really need the tray app. The service should automatically start in the background and doesn't require the icon being open.


I understand that it's coming back as an autostart, but do you use the icon for anything?

**Comment by happyguy1** [comment]
> If it's running as a service, you don't really need the tray app. The service should automatically start in the background and doesn't require the icon being open.
> 
> I understand that it's coming back as an autostart, but do you use the icon for anything?

Hi Anthony - first, let me say thank you for the awesome effort that you have put into Jellyfin!  It is SUPER appreciated!!

My issue is that since i set jellyfin as a server (which is useful as i always want it running), it always loads with autostart enabled. 

If i then reboot before manually unchecking the autostart, i will always get the above error on reboot, and have to go through those steps

My workaround solution is that i always have to remember to uncheck autostart after each reboot so that the next reboot doesn't trigger the error - however, unchecking autostart is not permanent, since the server always starts it unless it was previously manually unchecked.

Also, yes, i do appreciate having the icon in case i want to stop Jellyfin, although that functionality is not essential.

thanks so much again!!

best
steve

**Comment by jw2kfr** [comment]
I'm having this same issue - I originally set up the jellyfin service, at install, to use a custom login account as opposed to run it with the systems account.  After getting this error message I went back to using the system account for the service (in services manager).  However after booting I get the same error message as a popup, and the service does not auto-start (set to delayed auto).  I can then start the service manually, but when I come back to the system tray and right-click on the jellyfin icon

**Comment by tdnzr** [comment]
Have the same issue (on Windows 11, after installing jellyfin via winget): After every reboot, I get the popup "When running Jellyfin as a service, the tray application must be run as administrator".

**Comment by JohnRo79** [comment]
what i've done was to just hide the tray from Displaying fully (minimized it)
(right click on TaskBar)

<img width="1608" height="1211" alt="Image" src="https://github.com/user-attachments/assets/b1946f32-8217-40b9-8900-7ef699020b19" />
