### ISSUE TITLE
[10.8.0][Issue]: Unable to launch the Tray App

### ISSUE THREAD

**Issue by EdiTurn** [jellyfin/jellyfin-server-windows#57]
Jellyfin Version: 10.8.0-beta 1
OS: Windows Server 2022
Log: 

> Application: Jellyfin.Windows.Tray.exe
CoreCLR Version: 6.0.322.12309
.NET Version: 6.0.3
Description: The process was terminated due to an unhandled exception.
Exception Info: System.IO.FileLoadException: Could not load file or assembly 'System.Drawing.Common, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
File name: 'System.Drawing.Common, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at Jellyfin.Windows.Tray.TrayApplicationContext.CreateTrayIcon()
   at Jellyfin.Windows.Tray.TrayApplicationContext..ctor() in C:\repos\jellyfin-server-windows\Jellyfin.Windows.Tray\TrayApplicationContext.cs:line 70
   at Jellyfin.Windows.Tray.Program.Main() in C:\repos\jellyfin-server-windows\Jellyfin.Windows.Tray\Program.cs:line 17

**Comment by anthonylavado** [comment]
A new version was released to correct this at around 04:30 UTC. The install file is "jellyfin_10.8.0_beta1b-windows-x64.exe".

Can you try that one and let me know if you're still having issues? It should just install over top of what you have.

**Comment by EdiTurn** [comment]
It works well now.
Thanks
