### ISSUE TITLE
10.8.1 Installer didn't terminate the existing instance correctly

### ISSUE THREAD

**Issue by vsviridov** [jellyfin/jellyfin-server-windows#65]
Upgrading from 10.8.0 to 10.8.1 using the installer yielded following error:
![image](https://user-images.githubusercontent.com/221684/176042360-b05f94fe-2f73-43cc-83e5-892259a03ce8.png)

After looking in the process manager, some residual instances of `jellyfin.exe` were still running, which prevented the installer from continuing. The tray icon was missing after the installer offered to shut down existing instance.

After killing the manually the installation completed.

**Comment by anthonylavado** [comment]
Hrm, I don't believe we actually have any code in the installer to close the tray app or server process at all actually.

**Edit:** If it's running as a service it will stop it, but not in user mode. We'll need to add that.

**Comment by nielsvanvelzen** [comment]
Two related Reddit posts today of users that tried to update:

- https://www.reddit.com/r/jellyfin/comments/wi4ln0/error_when_installing_newest_version_of_jellyfin/
- https://www.reddit.com/r/jellyfin/comments/wi19b1/i_broke_something_updating_from_1080_to_1083/

**Comment by anthonylavado** [comment]
Staring with 10.9, you do get a warning if Jellyfin is running, and the install will stop before anything happens.
