### ISSUE TITLE
Opening right-click menu causes an unclosable window to appear.

### ISSUE THREAD

**Issue by vsviridov** [jellyfin/jellyfin-server-windows#66]
Sometimes when I click on the tray app I get additional application icon in my task bar and a small chromeless window with no controls.

![image](https://user-images.githubusercontent.com/221684/177595524-28ffa4b0-4642-45a1-af4b-3b73db56f24d.png)

It can only be removed by restarting the tray app.

**Comment by anthonylavado** [comment]
Interesting. Thanks for the report! I'll have a look at it soon.

**Comment by vsviridov** [comment]
Looks like it might have been a local issue, as I noticed another tray application behaving similarly.

After restarting `explorer.exe` process the issue disappeared.
