### ISSUE TITLE
exec details in context menu

### ISSUE THREAD

**Issue by jimlynnjulian** [jellyfin/jellyfin-server-windows#67]
Thye tray exec has all the usual details when a context menu is brought up. The primary exec, however, has none.
The primary exec needs to have the version number so the installation status can be determined.
If an installation already exists, a new effort will 'update' only.
Allowing a new install to 'overwrite' a previous install, or remove a previous install, but keep the data, would be a good addition.

**Comment by jimlynnjulian** [comment]
First part:
![tray](https://user-images.githubusercontent.com/11785524/179658047-1f80824e-79c0-4447-a99d-e6ad9a597a5c.png)
![jfin](https://user-images.githubusercontent.com/11785524/179658061-944d8b47-c7fd-4f22-a721-a2ac74763f25.png)

**Comment by jimlynnjulian** [comment]
Second part:
When I install jellyfin and an installation already exists, the app will offer to 'update' or 'cancel.'
A useful change would be to allow the existing install to be removed/uninstalled by the app.
Not really a needed change but possibly useful.

**Comment by anthonylavado** [comment]
For the application properties, thanks for the heads up. I'm not sure why that's not being populated, so I can dig in to .NET apps and verify.

For the install part, there is an uninstaller - this is what gets called if you go to the Control Panel > Add/Remove Programs section, or the Settings > Apps section, and choose "Uninstall". It gives you the option to uninstall and keep your user data, or to uninstall and remove user data. Is that what you're looking for?
