### ISSUE TITLE
[Issue]: Some text is unreadable in Jellyfin Server 10.8.3 Installer

### ISSUE THREAD

**Issue by gitname** [jellyfin/jellyfin-server-windows#68]
### Please describe your bug

The "Setup Type" screen in the Jellyfin Server 10.8.3 Installer (i.e. `jellyfin_10.8.3_windows-x64.exe`) shows the top part of some bold, red characters. I failed to find a way to reveal the full characters, so do not know what the text says. I have attached a screenshot below.

### Jellyfin Version

Other

### if other:

10.8.3

### Environment

```markdown
- OS: Windows 10 Enterprise LTSC Evaluation (version 1809)
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/7143133/182919914-c1b58971-d9e9-46b0-ac9e-5f7f5102f782.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anthonylavado** [comment]
Hrm that's a new one.

it's this line in the installer dialogs: https://github.com/jellyfin/jellyfin-server-windows/blob/ccbf275e63104fb565cd3b26c28c7f91c6a6983c/nsis/dialogs/setuptype.nsdinc#L35


I'll have a look later.

**Comment by anthonylavado** [comment]
I figured out the issue and did eventually correct it. Te text box was right up against a label, so even though it _looked_ ok in NSIS Dialog Designer, it would be rendered incorrect by NSIS itself.
