### ISSUE TITLE
Jellyfin won't open after system restart

### ISSUE THREAD

**Issue by jorgeBulgarelli** [jellyfin/jellyfin-server-windows#69]
I've installed Jellyfin v10.8.4 on Windows 11 Home OS build 22000.978.

The program runs great after installing, but as soon as I restart my computer, neither the tray .exe nor jellyfin.exe will open.

I've tried the different approaches on previous issues but none worked.

I've attached my logs file and hope this can be resolved as I love this service and wouldn't like to switch over to a different service.
[log_20220915.log](https://github.com/jellyfin/jellyfin-server-windows/files/9579969/log_20220915.log)

**Comment by anthonylavado** [comment]
That's odd. Does the shortcut in the start menu work? I think it's labelled "Jellyfin Server (View Console)".

**Comment by jorgeBulgarelli** [comment]
The shortcut in the start menu disappaears as soon as I hover the cursor
over it, when looking at the Task Manager as I'm doing it, the Jellyfin
process shows there but is closed instantly with the pattern described
above regarding the icon on the Task Bar

**Comment by kingdomcome82** [comment]
I got exactly the same behaviour. I've reinstalled and the tray icon now no longer disappears on hovering, but I can't access the server at all. I get the following on trying to open "We're unable to connect to the selected server right now. Please ensure it is running and try again.". 

At a bit of a loss in all honesty.

**Comment by Maxcension** [comment]
Same thing happened for me, simply upgraded Jellyfin by relaunching the `jellyfin_10.8.8_windows-x64.exe` worked!

**Comment by kennyng88** [comment]
Using JellyFin [installer/jellyfin_10.8.9_windows-x64.exe]. Installed a fresh window 10 yesterday. JellyFin was working. Scheduled update restart over the night. Woke up to JellyFin not booting up, tray wont stay open and no logs to read. Reinstall same version and is working now.

**Comment by jefflorenzini** [comment]
I also have the exact same problem. Every time I reboot, I have to reinstall the server to get it to load.
