### ISSUE TITLE
[Issue]: Bug in Windows installer

### ISSUE THREAD

**Issue by ThomasPGH** [jellyfin/jellyfin-server-windows#70]
### Please describe your bug

I updated from 10.8. something to the latest release 10.8.5 earlier today.
I have Jellyfin installed and running as a service on Windows.
Due do another issue I keep encountering after every update (the installer fails to keep my Jellyfin config and data folder as it is), I had `nssm edit "Jellyfin Server"` opened from a command-line window just before the installation.
The installer complained that nssm.exe is in use, hence I closed nssm (and the command-line window, although this might be irrelevant), then opted for Retry. Nssm.exe was then replaced and Jellyfin ran fine.

However, an hour later I had to reboot the machine for a different reason and the Jellyfin service wouldn't start because nssm.exe was missing.

My assumption is that because nssm.exe had been in use during the installation, the installer created an entry in the registry to delete nssm.exe after the next restart.

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS:
- Virtualization:
- Clients:
- Browser:
- FFmpeg Version:
- Playback Method:
- Hardware Acceleration:
- Plugins:
- Reverse Proxy:
- Base URL:
- Networking:
- Storage:
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anthonylavado** [comment]
Hrm, that's interesting. We don't create any entries in the Registry for cleanup as part of a uninstall/reinstall operation. I'm not entirely sure why NSSM would have disappeared.

Over the years NSSM will sometimes get flagged as malware (after all it can run any executable you configure as a service). Do you have any anti-malware or anti-virus tools that might have removed it at all?

I'm thinking about ways to replace NSSM for 10.9, but it would still be useful to gather any extra info for now.

---

Regarding your directory bug, on the readme of this repository (the Windows package), there's a section on where we look for paths with the installer/commands: https://github.com/jellyfin/jellyfin-server-windows#usage

If you look at the Registry Keys listed there, do the paths match what you expect? If not, just edit them and that _should_ keep things correctly for the next update.

**Comment by ThomasPGH** [comment]
Thanks. I'll try to find the AV logs later to see if it removed the file.

The link to those registry keys is also very interesting. Thanks again.
The key DataFolder points to the correct location but contrary to the link the value of ServiceAccountType is set to "None" instead of "NetworkService", which is the service account that runs the Jellyfin service. I'll check this next time before and after an update.
