### ISSUE TITLE
[Issue]: "Open Jellyfin" no longer specifes port - will not open web interface properly.

### ISSUE THREAD

**Issue by rsg73** [jellyfin/jellyfin-server-windows#71]
### Please describe your bug

1.  Right click Jellyfin taskbar icon in Windows 10 while Jellyfin server is running.
2.  Select "Open Jellyfin"

In the past this would open a browser window to localhost:8096 which would open the Jellyfin web interface.  Since v 10.8 this no longer happens.  When "Open Jellyfin" is selected, the browser tries to open "localhost/web/index.html" which throws an error as the port is not specified.  When the port is added manually it opens normally.

Is this the intended behavior now, or is there a setting that needs to be modified, or did somebody just forget to add the port in to the address?   Again, I have never had this problem prior to 10.8.X

Selecting this:
![image](https://user-images.githubusercontent.com/37202300/194721961-fba94946-57ac-447b-aa8f-cc0d47e157de.png)

Returns This:
![image](https://user-images.githubusercontent.com/37202300/194721986-0a2fffb5-b925-4ee9-861b-e8474dca757c.png)

And subsequently this:
![image](https://user-images.githubusercontent.com/37202300/194722147-cdcc72bf-28c1-4942-b864-7512bc4bd2a5.png)

### Jellyfin Version

10.8.0

### Environment

```markdown
- OS: Win 10 Pro
- Virtualization: n/a
- Clients: Browser
- Browser: Firefox/Chrome/Edge (i.e. all)
- FFmpeg Version: n/a
- Playback Method: n/a
- Hardware Acceleration: n/a
- Plugins:n/a
- Reverse Proxy: n/a
- Base URL: n/a
- Networking: n/a
- Storage: n/a
```

### Please attach any screenshots here

![image](https://user-images.githubusercontent.com/37202300/194722106-ef7ebba1-156d-4981-9a52-96bff2a84786.png)

![image](https://user-images.githubusercontent.com/37202300/194722116-778b732b-7476-4f7b-bf7b-f4c30637d74c.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rsg73** [comment]
Thanks Anthony, that was indeed the problem.  

<PublicPort>was set to 80.  Switching to 8096 did the trick.

Is there a reason it was set to 80 by default?

Cheers!

**Comment by anthonylavado** [comment]
@rsg73 It should be from the UI, the last time I checked.

Dashboard > Advanced > Networking. Set the public port, scroll down and click Save.

![image](https://user-images.githubusercontent.com/596194/194733392-7d0bb8c1-9915-478c-8320-07f3b49bb2f3.png)

**Comment by rsg73** [comment]
Hi Anthony.  I figured out what is going on.  

Dashboard>Advanced>Networking>Remote Access Settings

I changed the "Public HTTP Port Number" and restarted the server - and this in turn changed the PublicPort setting in the network.xml file.

I changed this:
![image](https://user-images.githubusercontent.com/37202300/194733670-1a92d3cd-9003-4a26-bc71-422098d4a5e4.png)

And after restarting the server, this was the result in config file.

![image](https://user-images.githubusercontent.com/37202300/194733700-f61ae775-5b8f-498a-b8ce-c4ee549874a9.png)

I just updated to 10.8.5 this morning, so assume its an issue with this build.

**Comment by anthonylavado** [comment]
You know what - I wonder if I'm grabbing the wrong field from the XML. I should be grabbing the local http port, not the public one. D'oh!

Will fix. It wouldn't be generally available unless at least the next release, but I should be able to make a hotfix build for you.

**Comment by rsg73** [comment]
"...grabbing the wrong field from the XML."  That is what I assumed.  

Unless other people are suffering, I don't think you need to spend time on a hotfix.  It is not causing any problems for me so I can wait until the next build - and I am sure you have more important things to work on.

Cheers :)
